language: generic s
sudo: require
services: 
  - docker

before_install:
  - docker build -t sierraoe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sierraoe/docker-react npm run test
