version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app/src
            - ./public:/app/public
        environment:
            - CHOKIDAR_USEPOLLING=true
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
            - ./public:/app/public
        command: ["npm", "run", "test"]